### ISSUE TITLE
Get `PINT` working

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#108]
I think we should re-factor `Pulsar` a bit so that it can use either `libstempo` or `PINT`. I think we should do this by making an `ltinterface` class as @vhaasteren had started a while ago.

**Comment by paulthebaker** [comment]
I agree we should support both.  If `ltinterface` is way out of date, maybe we should support `PINT` natively and wrap `libstempo`.

**Comment by jellis18** [comment]
@paulthebaker, at the moment we have all we need in the `Pulsar` class. So for our purposes we wouldn't really need a full libstempo-like interface. In principle I would like a function that reads in a `PINT` `TOA` object and `PINT` `model` object and returns an `enterprise` `Pulsar` object. This way we could use `PINT` from `enterprise` but also `enterprise` from `PINT`, which is what the developers want. So we just need to make this bridge.

**Comment by jellis18** [comment]
A lot of progress on this front has been made in PR #109.
