### ISSUE TITLE
Summary or description for Prior class

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#13]
As I was testing I found that I wanted an easy way to see what prior I was using. It may be nice to try to come up with some kind of summary method for the `Prior` class that displays the name of the distribution and maybe the parameters (i.e. mean, std for gaussian or limits on uniform, etc.).

We don't need this now but I wanted to start an issue so we don't forget.

**Comment by paulthebaker** [comment]
Some of these are properties of the `rv_continuous` class that are currently not carried over to the Prior class.  For instance `_stats` computes the mean, varience, skew, and kurtosis for the distribution.  There's also methods for the `mean`, `std`, `var`, `median`, `moments`.  We could add access to them pretty easily.

We could also add in some metadata variables that record the input domain or whatever else is not built into `rv_continuous`.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html

**Comment by paulthebaker** [comment]
`Prior` class is deprecated.
