### ISSUE TITLE
TypeError in data tutorial

### ISSUE THREAD

**Issue by pennucci** [nanograv/enterprise#139]
When running data.ipynb or just copy/pasting into ipython from the data tutorial, the 'efac1' class instance's method 'sample' doesn't appear to recognize the argument 'size'; executing efac1.sample() returns one sample, but I cannot pass it 'size=5':
TypeError                                 Traceback (most recent call last)
<ipython-input-7-a761d44cc7c4> in <module>()
     10 
     11 # return 5 samples from this prior distribution
---> 12 print(efac1.sample(size=5))

TypeError: sample() got an unexpected keyword argument 'size'

**Comment by pennucci** [comment]
I also get TypeErrors about the number of arguments of the Function sw2 at lines 12 and 14 in the notebook tutorial, when calling sw2() with no parameters and sw2(params=params), so I don't know if I've installed something wrong, or if this is outdated, or...?

**Comment by jellis18** [comment]
I've fixed the error in sample. We changed the syntax from using `size=5` to `n=5`

>> I also get TypeErrors about the number of arguments of the Function sw2 at lines 12 and 14 in the notebook tutorial, when calling sw2() with no parameters and sw2(params=params), so I don't know if I've installed something wrong, or if this is outdated, or...?

I don't get this error. Are you sure you did `python setup.py install` after getting the latest version?

**Comment by pennucci** [comment]
I thought I deleted the comment on that second TypeError; that was my fault, no issue.  BTW, the 9y tutorial needs an import deterministic_signals statement, or whatever, in case the ephemeris modeling is used.  Thanks!
