### ISSUE TITLE
Factors of 2pi needed to properly normalize likelihood

### ISSUE THREAD

**Issue by stevertaylor** [nanograv/enterprise#163]
Factors of 2*pi are not included in determinant factors in enterprise. This is fine when e.g. we keep the number of red noise components the same. But if we vary, or use different GP basis kernels, then likelihood values can not be compared across models in a model selection scenario.

**Comment by stevertaylor** [comment]
@jellis18 You've encountered problems like this before when doing model selection on the number of red noise components, right? I could go through the code and place 2*pi factors in the right places. It would be easy but tedious. It would be good to get some info on the correct places.

**Comment by jellis18** [comment]
I think you could probably add it [here](https://github.com/nanograv/enterprise/blob/master/enterprise/signals/signal_base.py#L191)

**Comment by stevertaylor** [comment]
Now I'm actually starting to doubt that we need it. In the hierarchical likelihood, we chain p(dt | b) with p(b | B). This gives us two determinant factors on the denominator. When we marginalize over "b", we end up with a factor of sqrt[ det(2 * pi * Sigma^{-1}) ] in the numerator. "B" and "Sigma" have the same size, so their factors of 2*pi cancel, leaving just 2*pi from the original N matrix. This makes sense since the marginalization should be equivalent to the dense representation with det(2 * pi * C) on the denominator, where C = N + C_red. 

Note that this is different than the way we used to do things i.e. with the G-matrix, since then we were marginalizing over the timing-model parameters with a uniform prior, not an infinite-variance Gaussian.

**Comment by vallis** [comment]
I think you're right Steve. See Eq. (2) in my GP review with Rutger.

The thing I've been worried about though is the accounting of timing-model parameters in the square-root determinant. Maybe those are regularized by measurement noise in the marginalized likelihood, but they would seem to create infinite Occam factors in the hierarchical likelihood.

**Comment by bvgoncharov** [comment]
Hi @stevertaylor , @vallis and @jellis18 ! Sorry for getting back to this closed issue, but is this still the case, that we can't really do GP process model selection between likelihoods with different GP basis kernels?

For example, when I do model selection between two models for uncorrelated red noise, where I use a different `gp_signals.FourierBasisGP(spectrum=model_spectrum, ...)` for each of `model_spectrum`. I think I might be seeing the effect of this issue.

**Comment by stevertaylor** [comment]
Hi @bvgoncharov. I think we settled on our likelihood not suffering from this issue. Even though all temporally correlated processes are described in some reduced-rank way, the likelihood itself is written in the time domain, so there only ever need to be as many factors of 2pi as there are total number of TOAs. This is model invariant, so it should not affect things. 

Perhaps you are experiencing sampling transition problems between models in your tests?

**Comment by bvgoncharov** [comment]
Hi @stevertaylor , ok, good to know, thanks!
It could be related to sampler transition problem, but not an obvious one, where the sampler is just "stuck" at one of the models.

Basically, I run model selection between a power law and a broken power law (uncorrelated red noise) using multiple white noise simulations from libstempo. And I see an overall preference for a broken power-law, while a regular power-law with fewer parameters should be favored by the Occam factor. Similarly, on average, a broken power-law is preferred when a regular power-law is injected.

**Comment by stevertaylor** [comment]
Hi @bvgoncharov. By broken power-law do you mean the turnover model or the free-spectrum model? It's worth checking that you are injecting and recovering with the same number of red frequency components. Also, the lower dimensional model will only be preferred if all else is equal-- it seems like the broken power-law is actually picking up some feature in your spectral injections or data.

**Comment by bvgoncharov** [comment]
Hi @stevertaylor , I mean the turnover model, i.e. PSD~(f+f_turnover)^(-gamma).
I always use 30 red frequency components, but for my results with white noise, it probably doesn't matter. Everything else in both models is the same: EFAC, EQUAD, and the timing model. 

As for spectral features, I currently think about these possibilities:
I noticed that in libstempo simulations are performed directly in "stoas" (at site), but not in SSB frame. 
In addition, I and @ZhuXJ1 think this could be the effect of marginalizing over a timing model (and for simulated pulsars with libstempo we don't even have a timing model).
