### ISSUE TITLE
Normalization for DM in utils.createfourierdesignmatrix_dm 

### ISSUE THREAD

**Issue by bvgoncharov** [nanograv/enterprise#164]
Hi All,

I have recently started to use Enterprise, and while resolving a discrepancy of my results with other person results (from PAL2) noticed the following. In [utils.createfourierdesignmatrix_dm](https://github.com/nanograv/enterprise/blob/2f7c3f48d5feac809819696e98ed095666bdcc55/enterprise/signals/utils.py#L107) we create a Fourier design matrix for DM variation noise. But it looks like there is a to-do item: # TODO: should we use a different normalization. 

Here are my suggestions:
1) Replace [line 134](https://github.com/nanograv/enterprise/blob/2f7c3f48d5feac809819696e98ed095666bdcc55/enterprise/signals/utils.py#L134) with the following:
`Dm = 4.15e3/(freqs**2)`
2) Add a comment:
`# 4.15e3 = K^(-1), where K is from Eq. 23 in L. Lentati paper: https://academic.oup.com/mnras/article/437/3/3004/2907742`

Do you think these are worth implementing?
I would be happy to git-push these changes.

**Comment by jellis18** [comment]
I would rather keep the current normalization which makes the basis functions dimensionless. There are several reasons for this.

1. Much easier to gauge "strength" of DM signal as with this normalization it is simply the deviation (in seconds) at 1.4 MHz.
2. Allows the exact same parameterization and priors as we use for red noise.
3. Keeps code uniform in that all basis functions are dimensionless and all gaussian priors are variances in units of seconds^2.
4. Allows for easy extension to other exponents on radio frequency (i.e. scattering, or varying, etc) without having to figure out what other constant to use for normalization

Of course this is up to the other developers as well but I strongly prefer the dimensionless normalizations.

**Comment by paulthebaker** [comment]
I also prefer to keep them dimensionless, but it would be pretty easy to allow the `create designmatrix` functions to take a normalization option.  The hardcoding of numbers always bothers me, even if I would choose 1400 MHz too.

**Comment by bvgoncharov** [comment]
@jellis18 @paulthebaker then we could just add "fref" argument in utils.createfourierdesignmatrix_dm, with a default of 1400, and mention that it has MHz units in the comment. It shouldn't affect existing users

**Comment by jellis18** [comment]
@bvgoncharov, that sounds good. Do you want to implement this and make a PR?

**Comment by bvgoncharov** [comment]
Hi @jellis18 , sure, I created a PR: https://github.com/nanograv/enterprise/pull/165
Sorry for late reply. This was my first pull request, so I had to find some time to look through documentation and make sure I am doing it right :)
