### ISSUE TITLE
put reqs in `setup.py`

### ISSUE THREAD

**Issue by paulthebaker** [nanograv/enterprise#198]
When `setup.py` runs it doesn't check if any requirements are satisfied. We use `requirements.txt` and `requirements_dev.txt` to setup the testing environment for Travis. These do not actually enforce anything for a user install.

If a user installs enterprise either using `pip` with `git+` or from source the requirements won't be checked during the install process.

**Comment by paulthebaker** [comment]
this should be addressed in PR #200

**Comment by jellis18** [comment]
Done in #257
