### ISSUE TITLE
Adding custom backend selection

### ISSUE THREAD

**Issue by siyuan-chen** [nanograv/enterprise#216]
Hi all,
regarding pull request #215 
I coded up a new selection function that allows for a more flexible user-specified backend selection into `selections.py` and created a pull request. However, the Travis CI fails at the <make lint black --check> stage. I guess that has to do with the PEP8 style guide. So, I did a local check on the file and it was fine according to PEP8 online check and black. @vallis @jellis18 , can you have a look? I see that also the previous pull request failed. Maybe, there are some none-PEP8 conforming files?
Thanks and cheers

**Comment by vhaasteren** [comment]
Closing, because #215 is closed
