### ISSUE TITLE
Duplicated logging when enterprise.pulsar is imported

### ISSUE THREAD

**Issue by swiggumj** [nanograv/enterprise#242]
In recent timing_analysis development our logging messages started getting duplicated once noise modeling pieces were added to the notebook, e.g.:
```
INFO: astropy: Removing ScaleToaError from model.
INFO: astropy: Removing EcorrNoise from model.
Removing pre-existing noise parameters
INFO: Removing ScaleToaError from model. [timing_analysis.lite_utils]
INFO: Removing EcorrNoise from model. [timing_analysis.lite_utils]
```
We think this has to do with lines like these in enterprise:
```
logging.basicConfig(format="%(levelname)s: %(name)s: %(message)s", level=logging.INFO)
```

Here's a quick test I did which may or may not be enlightening...
![Screen Shot 2021-01-14 at 5 17 42 PM](https://user-images.githubusercontent.com/4108303/104661115-78ae5300-568d-11eb-8633-062b6fb44bac.png)
![Screen Shot 2021-01-14 at 5 18 06 PM](https://user-images.githubusercontent.com/4108303/104661116-7946e980-568d-11eb-9247-cc2b6b8e6145.png)
![Screen Shot 2021-01-14 at 5 18 34 PM](https://user-images.githubusercontent.com/4108303/104661119-7946e980-568d-11eb-8691-1f6693e02a26.png)

**Comment by aarchiba** [comment]
It is not appropriate for libraries to configure loggers - top-level programs should configure their own logging behaviour.

**Comment by paulray** [comment]
I commented out the 4 places in enterprise where it calls `logger.basicConfig()` and the problem went away. So, I recommend that enterprise remove those lines.  If enterprise users need a special config, it can be done in a top level script.

**Comment by Hazboun6** [comment]
So, as @paulray mentioned elsewhere, removing the call 
```
logging.basicConfig(format="%(levelname)s: %(name)s: %(message)s", level=logging.INFO)
```
Will change what users see from enterprise output. Is the default level already set to `INFO` somewhere else? 

@vallis @paulthebaker do you have thoughts about this? Elsewhere @aarchiba suggested making a convenience function a user could call to duplicate the current behavior.

**Comment by swiggumj** [comment]
It seems this has fallen by the wayside... It would be really nice to get this resolved before the TWG starts reprocessing. @Hazboun6 @vallis @paulthebaker can we find a solution sometime this week?

**Comment by Hazboun6** [comment]
@swiggumj I've just opened PR #251 to make these changes. This still needs discussion from other `Enterprise` devs, but at least the PR is there.

**Comment by swiggumj** [comment]
Thanks @Hazboun6 !

**Comment by Hazboun6** [comment]
Since PR #251, which deals with this problem, was merged this issue can be closed.
