### ISSUE TITLE
Free Travis.org is being discontinued

### ISSUE THREAD

**Issue by Hazboun6** [nanograv/enterprise#243]
Travis is no longer supporting free services for continuous integration. Other NANOGrav software has been moved to GitHub Actions. See the [PsrSigSim](https://github.com/PsrSigSim/PsrSigSim/issues/177) and [Pint](https://github.com/nanograv/PINT/issues/817). Both of these have links to various resources for migrating to Actions.

**Comment by vallis** [comment]
Andrew Kaiser put together CI through actions.
