### ISSUE TITLE
Lets make enterprise legit!

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#252]
We (and by we I mean you) have done a good job with `enterprise` in terms of test coverage and documentation. However, we aren't releasing new versions and this package is not available on pypi.

I suggest 3 things to make this project more legit.

1. Commit to semantic versioning and release new tags accordingly (making a build and release action could make this easier)
2. Upload `enterprise` to pypi (would probably need to be called `enterprise-pulsar`)
3. Make a Docker image for `enterprise` that will allow a user to run a Jupyter notebook inside the container without having to install any dependencies (also would have a build and release target for this as an action)

I am willing to help with all of these things if you think they are worthwhile.

**Comment by jellis18** [comment]
@nanograv/enterprise 

I have been working on libstempo but I think [this comment](https://github.com/vallis/libstempo/issues/34) applies to enterprise as well.

**Comment by vallis** [comment]
This was mostly done... we're leaving Docker containers to the cyberI folks for the moment.
