### ISSUE TITLE
Remove soft replacement for missing sksparse

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#258]
In two places there are try-except statements that try to import sksparse and replace it with scipy otherwise. This prints or logs a message but I think we should get rid of this and require sksparse.

Especially after #257 is merged and `scikit-sparse` becomes an official dependency

**Comment by vallis** [comment]
I support requiring sksparse and not defaulting to scipy: it's too confusing to support sparse cholesky through different libraries. Please go ahead with a PR if you have the code ready.

**Comment by jellis18** [comment]
@vallis I'll get to this soon. I was off last week, hence the burst of activity but now it may have to wait til the weekend.

**Comment by vallis** [comment]
Solved by @jellis18 with #260
