### ISSUE TITLE
YUPPI is not listed as a NANOGrav backend

### ISSUE THREAD

**Issue by NihanPol** [nanograv/enterprise#291]
Title says it all. Need to add YUPPI as a NANOGrav backend, starting at the 15 yr dataset.

**Comment by NihanPol** [comment]
Solution in MR  #292

**Comment by Hazboun6** [comment]
Also VEGAS and whatever the CHIME backend is called...

**Comment by vallis** [comment]
Should we close this, or can we get those backend names in?

**Comment by NihanPol** [comment]
whoops, this was addressed long ago. closing now (though we might need to revisit once VEGAS data starts coming in).
