### ISSUE TITLE
Fix astropy._erfa Import to use pyerfa instead

### ISSUE THREAD

**Issue by JPGlaser** [nanograv/enterprise#328]
As it says on the tin. See the below import error that always appears.

```
+ python -c from enterprise.pulsar import Pulsar
WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]
```

~ Joe G.

**Comment by vallis** [comment]
This warning comes from code inside PINT... looking there, astropy._erfa is imported as a fallback if pyerfa is not available.

Now, I see that pyerfa is included in requirements.txt, but not in setup.py/setup.cfg. That means that it is only installed with "pip install -r", but not, e.g., when PINT is installed in the course of the enterprise install.

I think the solution here is to include pyerfa in PINT's setup.cfg.

**Comment by aarchiba** [comment]
This is fixed now: https://github.com/nanograv/PINT/pull/1508

**Comment by AaronDJohnson** [comment]
Closed as completed
