### ISSUE TITLE
Black settings ask for python 3.8 compatible syntax but enterprise supports python 3.7

### ISSUE THREAD

**Issue by aarchiba** [nanograv/enterprise#342]
`pyproject.toml` has a setting to determine which version of Python `black` should produce syntax for; this should be the oldest version on which enterprise is expected to run, but it isn't:

https://github.com/nanograv/enterprise/blob/master/pyproject.toml#L3

As result, `black` could reformat our code in a way that doesn't run on our test suite.

**Comment by AaronDJohnson** [comment]
Personal opinion: it's not worth worrying about 3.7 as its end of life is in 4 months (https://endoflife.date/python). I think we should drop 3.7 in anticipation of this event and make a move to support 3.11 instead.

**Comment by AaronDJohnson** [comment]
Personal opinion: We should drop support for Python 3.7 and move to support 3.11 instead since 3.7 reaches EoL in 4 months (https://endoflife.date/python)

**Comment by vhaasteren** [comment]
We removed 3.7 with #362
