### ISSUE TITLE
Support for Python 3.11?

### ISSUE THREAD

**Issue by rossjjennings** [nanograv/enterprise#350]
Currently Enterprise cannot be installed in a Python 3.11 environment (`python-requires=">=3.7,<3.11"` in `setup.py`). I don't know how hard it would be to remove this restriction -- is it as simple as bumping the version cap, or is there a real incompatibility? In any case, it's something to think about, especially since 3.11 is now the default Python version on conda-forge.

**Comment by vhaasteren** [comment]
Solved by #362
