### ISSUE TITLE
A bug in gp_signals.py

### ISSUE THREAD

**Issue by hdeng01** [nanograv/enterprise#358]
In signals/gp_signals.py, there seems to be a bug in the function `solve(self, right, left_array=None, logdet=False)` under `class MarginalizingNmat(object)`. If we model a pta with `gp_signals.MarginalizingTimingModel`, the following code
`Nvecs = pta.get_ndiag(x0)`
`res = psrs[0].residuals`
`print(Nvecs[0].solve(res, res))`
leads to error "cannot unpack non-iterable numpy.float64 object".
Seems that under the first if statement,
`rNr, logdet_N = self.Nmat.solve(res, left_array=res, logdet=logdet)`
should be replaced by something like
`if logdet:`
`    rNr, logdet_N = self.Nmat.solve(res, left_array=res, logdet=logdet)`
`else:`
`    rNr = self.Nmat.solve(res, left_array=res, logdet=logdet)`

**Comment by vhaasteren** [comment]
Thanks for the report. I created a simple bugfix for it: #359

**Comment by vhaasteren** [comment]
Solved by #359
