### ISSUE TITLE
Merge dev to master

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/enterprise#385]
Let's merge dev into master and do a new Enterprise release. @AaronDJohnson, @vallis, others, what would you like to get added/modified before then?

**Comment by AaronDJohnson** [comment]
I think moving to support Python 3.12 should be trivial too, so we might as well get that going.

**Comment by vhaasteren** [comment]
On my M1 macbook pro, healpy is not a problem. Pip chokes on scikit-sparse and libstempo. Realistically, we don't need either. Sparse matrix operations actually don't help that much either.

**Comment by vhaasteren** [comment]
@AaronDJohnson, pip/python allows optional dependencies with extras_require, such as this way:

```python
# Core requirements
requirements = [
    "numpy>=1.16.3",
    "scipy>=1.2.0",
    "ephem>=3.7.6.0",  # This might be a core requirement, or could be optional, depending on your package
]

# Optional dependencies
extras_require = {
    'full': [
        "healpy>=1.14.0",
        "scikit-sparse>=0.4.5",
        "pint-pulsar>=0.8.3",
        "libstempo>=2.4.4",
    ]
}
```

Perhaps healpy, which is less problematic, can be in a separate extra also. Then you can install with either:

`pip install enterprise-pulsar`

or

`pip install enterprise-pulsar[full]`

Problem with this is backward compatibility in, say, Dockerfiles, which might not have `full` selected. But optional dependencies cannot be on by default.

**Comment by AaronDJohnson** [comment]
Hopefully they pinned their versions in those old Dockerfiles...
