### ISSUE TITLE
libstempo updates

### ISSUE THREAD

**Issue by mattpitkin** [nanograv/enterprise#388]
Hi enterprise devs! I've put together a MR for libstempo that does some updates to the build system, drops support for Python 3.7 and makes the build NumPy 2.0 compatible https://github.com/vallis/libstempo/pull/69. If there's anything that would be useful to include from an enterprise point-of-view, please comment on the MR.

**Comment by AaronDJohnson** [comment]
I don't think there is anything in particular that we need. We should probably drop support for 3.7 here too though.

**Comment by mattpitkin** [comment]
Version 2.5.0 of libstempo is now released and available through PyPI and conda-forge.
