### ISSUE TITLE
Missing left_array in MarginalizingNmat.solve

### ISSUE THREAD

**Issue by JacobCT** [nanograv/enterprise#401]
When trying to calculate the Fe statistic, we came into a problem located in the `solve` function (line 860) of gp_signals.py. When both the variables `right` and `left_array` are two-dimensional and are not the same, they are not covered by the elif conditions currently present.

**Comment by vhaasteren** [comment]
Yes, I knew about this thing missing. Great that you are submitting a PR, thank you
