### ISSUE TITLE
Test out sparse matrix speed for full PTA band diagonal matrix

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#56]
In the current codes (i.e. `PAL2`, `NX01`, `piccard`) we use a scheme where we invert individual `npsr` x `npsr` blocks of the full PTA phi matrix. This is very fast but it requires a lot of bookkeeping. We would like to try out some sparse matrix algebra to see if inverting this band diagonal matrix via sparse methods is comparable to the block method. 

Unless the sparse matrix is significantly slower we should start with this method in the `PTA` code base but should allows for generic methods that will have `solve` methods. That way, the user can specify which method to use but the API remains the same.

@stevertaylor, can you look in to this?

**Comment by stevertaylor** [comment]
I'm on it.

**Comment by stevertaylor** [comment]
![image](https://cloud.githubusercontent.com/assets/5446644/26085662/b7a2d978-399a-11e7-9b77-7459437e6a81.png)

**Comment by stevertaylor** [comment]
The plot above shows the relative evaluation time (sparse / frequency-wise) for the big phi inversion. Sparse is only better for fewer than ~8 pulsars. (The number of timing model parameters was assumed to be 100, and the number of red modes was 30. However the actual phi inversion was performed for the red processes only, then the big phiinv was filled in with the results.)

**Comment by stevertaylor** [comment]
![image](https://cloud.githubusercontent.com/assets/5446644/26088200/9bd0fe5e-39aa-11e7-944d-d27b8981def4.png)

**Comment by stevertaylor** [comment]
The above plot shows the time for the entire big Phi formation, inversion, big Sigma formation, and big Sigma inversion. We should **always** be using sparse inversion for big Sigma. Sparse inversion of big Phi costs slightly with respect to frequency-wise inversion of Phi, but it is ~20% at most. If book-keeping is much easier for the sparse inversion of big Phi, then I think we should use it.

**Comment by stevertaylor** [comment]
There is a costly step in the likelihood which I had not appreciated before. `Sigma = bigTtNT + Phiinv` is very expensive. Perhaps we should form big Sigma all at once.

**Comment by jellis18** [comment]
@stevertaylor, yes I think it may be because it is creating a new matrix for Sigma. It should be stored in the `Likelihood` class and filled in as we go.

**Comment by stevertaylor** [comment]
@jellis18 Yes, I just did some tests with `Phi += bigTtNT` instead and that was already better.

**Comment by stevertaylor** [comment]
OK, hopefully this issue is now resolved. I will upload my jupyter notebook to slack. It is stand-alone so you can play around with it. It seems that the ease of using sparse algebra on big Phi is a 20% cost at most, which we can probably get back through other optimizations.

**Comment by paulthebaker** [comment]
@stevertaylor, initialization of the matrices eats up a bunch of time. At the hackathon there were gains for carrying around Sigma and it's cholesky factorization in a class.  They would be overwritten each evaluation, but they wouldn't have to be initialized and freed.

**Comment by jellis18** [comment]
I think we are good with this now as was addressed in PR #89
