### ISSUE TITLE
How do we subclass signals?

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#90]
Currently all signals are defined by class factories of the form 
```python
def SignalName(*args, **kwargs):
     class SignalName(Signal):
         def __init__(self, psr):

    # define things here

    return SignalName
```
The question is how can we subclass the specific signal class? For example we have `FourierBasisGP` signals for red noise but a `DMFourierBasisGP` factory would be identical except the `F` matrix and parameter names would be different. We **definitely** need some way of doing this, otherwise we are going to be re-writing a lot of code.

Any thoughts?

**Comment by vallis** [comment]
This works:

```python
def DerivedSignalName(*args, **kwargs):
     class DerivedSignalName(SignalName(*args,**kwargs)):
          # override methods here

     return DerivedSignalName
```

Is it confusing?

**Comment by jellis18** [comment]
@vallis, this is good but we may need to re-work some of the signals to be modular enough so that we minimize re-writing of code when sub-classing.

**Comment by jellis18** [comment]
I think this is good now. I'm closing this issue.
