### ISSUE TITLE
How to do upper limits (i.e. how to put linear priors on log parameters)?

### ISSUE THREAD

**Issue by jellis18** [nanograv/enterprise#98]
I have just started testing and wanted to re-create the 9-year upper limit. However, we currently don't have a good way to put linear priors on log parameters. Of course we could hardcode something but I think we should have the parameter somehow know if the parameter is log or not.

Any thoughts?

**Comment by jellis18** [comment]
OK, for now I have added a new prior type with this generator 
```python
class _linear_exp_gen(rv_continuous):
    """A distribution with pdf(x) ~ 10^x."""

    def _rvs(self):
        return np.log10(np.random.uniform(10**self.a, 10**self.b, self._size))

    def _pdf(self, x):
        return np.log(10) * 10**x / (10**self.b-10**self.a)

    def _logpdf(self, x):
        return np.log(self._pdf(x))

    def _cdf(self, x):
        return np.log(10) * (10**self.a - 10**x) / (10**self.a - 10**self.b)
```

And I have made a corresponding parameter `LinearExp`. So when declaring red noise amplitudes you can do `log10_A = parameter.LinearExp(-18, -12)` and this will give a uniform (not log-uniform) prior.

**Comment by jellis18** [comment]
I'll leave this open for now but it seems to be a good solution unless we end up with some sort of Jacobian structure later

**Comment by vallis** [comment]
This seems *the* way to do it.

Unless you'd rather sample the linear parameter (is that more efficient), and convert it on use. That's an interesting problem! It leads into a unification of `Parameter` with `Function`. Then `Parameters` would usually be evaluated trivially (the return their own value plucked from `params`), but in cases like this they would compute a translated (here, exponentiated) value. We can think about this.

**Comment by jellis18** [comment]
> Unless you'd rather sample the linear parameter (is that more efficient), and convert it on use. That's an interesting problem! It leads into a unification of Parameter with Function. Then Parameters would usually be evaluated trivially (the return their own value plucked from params), but in cases like this they would compute a translated (here, exponentiated) value. We can think about this.

Maybe we would want something like this from other parameters but for log parameters that vary over order of magnitude it is way more efficient to sample in the log of the parameter.
